graphite_settings:
    hosts:
        - 'mygraphiteserver1.example.com:2024'
        - 'mygraphiteserver2.example.com:2024'

performance_counters:
    metric_prefix: 'one_min.test.perfcounters'
    interval: 5
    counters:
        - '\Network Interface(*)\Bytes Received/sec'
        - '\Network Interface(*)\Bytes Sent/sec'
        - '\Processor(_Total)\% Processor Time'

sql_metrics:
    sql_servers:

        - connection_string: "server=mssql.example.com;user id=sa;password=sa"
          queries:

                # example of the query which return rows, column_name will be interpreted as METRIC-NAME SUFFIX, row_value  - as METRIC VALUE
                - interval: 10                                         # in seconds
                  tsql_row: 'select @@CONNECTIONS as CONNECTIONS'
                  timestamp: now                                       # specify column name which will be interpreted as metric timestamp or leave as is
                  metric_prefix: 'one_min.test.sql'

        - connection_string: 'server=localhost;user id=WIN\admin'      # supports windows auth
          queries:
                - interval: 30
                  tsql_row: 'select @@CPU_BUSY as CPU_BUSY, @@IO_BUSY as IO_BUSY'
                  metric_prefix: 'one_min.testv.%hostname%.sql'        # %hostname% will be interpreted as local hostname

                # example of the query which return a simple table with two colums, first column will be interpreted as METRIC-NAME SUFFIX, second - as METRIC VALUE,
                # third (optional) - as METRIC TIMESTAMP
                - interval: 30
                  tsql_table: 'SELECT DB_NAME(dbid), COUNT(dbid) FROM sys.sysprocesses WHERE dbid > 0 GROUP BY dbid'
                  timestamp: now
                  metric_prefix: 'one_min.network'
