graphite_settings:
    hosts:
        - 'mygraphiteserver1.example.com:2024'
        - 'mygraphiteserver2.example.com:2024'

performance_counters:
    metric_prefix: 'one_min.test.perfcounters'
    interval: 5
    counters:
        - '\Network Interface(*)\Bytes Received/sec'
        - '\Network Interface(*)\Bytes Sent/sec'
        - '\Processor(_Total)\% Processor Time'

sql_metrics:
    sql_servers:
        - metric_prefix: 'one_min.test.sql'
          connection_string: "server=mssql.example.com;user id=sa;password=sa"
          queries:
                - interval: 10                                    # in seconds
                  tsql: 'select @@CONNECTIONS as CONNECTIONS'
                  type: 'single-row'                              # the query should return single row, column_name will be interpreted as METRIC SUFFIX, row_value  - as METRIC VALUE
        - metric_prefix: 'one_min.testv.%hostname%.sql'           # %hostname% will be interpreted as local hostname
          connection_string: 'server=localhost;user id=WIN\admin' # supports windows auth
          queries:
                - interval: 30
                  tsql: 'select @@CPU_BUSY as CPU_BUSY, @@IO_BUSY as IO_BUSY'
                  type: 'single-row'
                - interval: 30
                  tsql: 'SELECT DB_NAME(dbid), COUNT(dbid) FROM sys.sysprocesses WHERE dbid > 0 GROUP BY dbid'
                  type: 'key-value'                               # the query should return a simple table with two colums, first column will be interpreted as METRIC SUFFIX, second - as METRIC VALUE
